name: Release Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.1)'
        default: 'v1.0.1'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          TAG_NAME="${{ github.event.inputs.version }}"
        else
          TAG_NAME="${GITHUB_REF#refs/tags/}"
        fi
        VERSION="${TAG_NAME#v}"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
        
    - name: Update manifest version
      run: |
        sed -i 's/"version": "[^"]*"/"version": "${{ steps.get_version.outputs.VERSION }}"/' extension/manifest.json
        
    - name: Create extension package
      run: |
        cd extension
        zip -r "../random-form-filler-${{ steps.get_version.outputs.TAG_NAME }}.zip" .
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.TAG_NAME }}
        name: "Random Form Filler ${{ steps.get_version.outputs.TAG_NAME }}"
        files: random-form-filler-${{ steps.get_version.outputs.TAG_NAME }}.zip
        generate_release_notes: true